/**
 * rand_mto.h - file containing declaration of functions for many-to-one random
 * 				number generation(Fibonacci configuration)
 * @author Aleksandar Andjelkovic
 * @time 03-04-2026 17:23
 */

#ifndef RAND_MTO_H_
#define RAND_MTO_H_

#include "logic_utils.h"

/**
 * InitRand - set seed for random number generation
 * @param seed - starting number of the generator
 * @return none
 */
void InitRand(uint16_t seed);

/**
 * Rand - function that generates random number
 * @return generated number
 */
uint16_t Rand();

/**
 * RandRange - function generating random number from min to max range
 * @param min - minimal value that can be generated
 * @param max - maximal value that can be generated
 * @return generated number
 */
uint16_t RandRange(uint16_t min, uint16_t max);

/**
 * GenerateNextBit - function that generates next MSB of random number
 * 					 base on current state
 * @param current_state - last generated random number
 * @return generated bit
 */
uint8_t GenerateNextBit(uint16_t current_state);

/**
 * UpdateState - function that updates state of random number generator
 * @param state - current state of the generator
 * @param bit - bit generated by GenerateNextBit
 * @return generated register state state
 */
uint16_t UpdateState(uint16_t state, uint8_t bit);

#endif /* RAND_MTO_H_ */

